app:
  link-updater-scheduler:
    interval: 60s
  base-url:
    git-hub: https://api.github.com
    bot: ${BOT_BASE_URL:http://localhost:8090}
    stack-overflow: https://api.stackexchange.com/2.3
  timeout:
    minutes: 5
  database-access-type: jdbc

spring:
  application:
    name: scrapper
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:54322/scrapper}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
