app:
  telegram-token: ${BOT_TOKEN:"some_token"}
  base-url:
    scrapper: ${SCRAPPER_BASE_URL:"http://localhost:8080/"}
  timeout:
    minutes: 5

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:54321/bot}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    enabled: false

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
