app:
  telegram-token: ${BOT_TOKEN}

scrapper:
  base:
    url: "http://localhost:8080/"
  timeout:
    minutes: 5

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
