app:
  telegram-token: "6490724857:AAHToyHsxpCngTYHDVNZGrRZiQwaAlwCwww"

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
